---
title: "covid19_proj"
author: "RockDeng"
date: "2024-10-09"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries
library(tidyverse)
library(lubridate)
```


```{r}
url_in <- "https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/"

file_names <- c("time_series_covid19_confirmed_US.csv",
               "time_series_covid19_deaths_US.csv",
               "time_series_covid19_confirmed_global.csv",
               "time_series_covid19_deaths_global.csv")

urls <- str_c(url_in, file_names)

local_file_names <- c("time_series_covid19_confirmed_US.csv",
                      "time_series_covid19_deaths_US.csv",
                      "time_series_covid19_confirmed_global.csv",
                      "time_series_covid19_deaths_global.csv")

```

```{r}
us_cases <- read_csv(local_file_names[1])
us_deaths <- read_csv(local_file_names[2])
global_cases <- read_csv(local_file_names[3])
global_deaths <- read_csv(local_file_names[4])

#us_cases <- read_csv(urls[1])
#us_deaths <- read_csv(urls[2])
#global_cases <- read_csv(urls[3])
#global_deaths <- read_csv(urls[4])

```

### Tidy the dataset

```{r}
global_cases_pivot <- global_cases %>%
  pivot_longer(cols = -c('Province/State',
                         'Country/Region',
                         Lat, 
                         Long),
               names_to = "date",
               values_to = "cases") %>%
  select(-c(Lat,Long))

global_deaths_pivot <- global_deaths %>%
  pivot_longer(cols = -c('Province/State',
                         'Country/Region',
                         Lat, 
                         Long),
               names_to = "date",
               values_to = "deaths") %>%
  select(-c(Lat,Long))




```
```{r}
global <- global_cases_pivot %>%
    full_join(global_deaths_pivot) %>%
    rename(Country_Region = "Country/Region",
           Province_State = "Province/State") %>%
    mutate(date = mdy(date))
```

```{r}
us_cases_pivot <- us_cases %>%
    pivot_longer(cols = -(UID:Combined_Key),
                 names_to = "date",
                 values_to = "cases") %>%
    select(Admin2:cases) %>%
    mutate(date = mdy(date)) %>%
    select(-c(Lat, Long_))

us_deaths_pivot <- us_deaths %>%
    pivot_longer(cols = -(UID:Combined_Key),
                 names_to = "date",
                 values_to = "deaths") %>%
    select(Admin2:deaths) %>%
    mutate(date = mdy(date)) %>%
    select(-c(Lat, Long_))
```

```{r}
global <- global %>%
    unite("Combined_Key", 
          c(Province_State, Country_Region),
          sep = ", ",
          na.rm = TRUE,
          remove = FALSE)

```

```{r}
uid <- read_csv("UID_ISO_FIPS_LookUp_Table.csv") %>%
    select(-c(Lat, Long_, Combined_Key, code3, iso2, iso3, Admin2))
```

```{r}
global_p <- global %>%
    left_join(uid, by=c("Province_State", "Country_Region")) %>%
    select(-c(UID, FIPS)) %>%
    select(Province_State, Country_Region, date, cases, deaths, Population, Combined_Key)
```
